

services:
  flask_app:
    build:
      context: .
      target: dev  # Change to "prod" for production
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app  # Sync local files for live development
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: flask_db
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load credentials from .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
