"""empty message

Revision ID: 3b283372e7e4
Revises: d7ee482c6b32
Create Date: 2025-02-16 18:44:16.149046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b283372e7e4'
down_revision = 'd7ee482c6b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lists_tasks',
    sa.Column('lists_id', sa.Integer(), nullable=True),
    sa.Column('tasks_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lists_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['tasks_id'], ['tasks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lists_tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
