"""empty message

Revision ID: 647163c79b21
Revises: 0208cb51964b
Create Date: 2025-02-16 18:38:46.164345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647163c79b21'
down_revision = '0208cb51964b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lists')
    # ### end Alembic commands ###
